openapi: 3.0.3
info:
  title: Book Management API
  version: 1.0.0
  description: |
    API cho phép quản lý danh sách sách bao gồm:
    - Xem danh sách các sách
    - Thêm sách mới
    - Cập nhật thông tin sách
    - Xóa sách
    - Lấy chi tiết sách theo ID

servers:
  - url: http://localhost:8000
    description: Local server

paths:
  /books:
    get:
      summary: Lấy danh sách tất cả sách
      description: Trả về danh sách tất cả các sách hiện có trong hệ thống.
      responses:
        '200':
          description: Danh sách sách được trả về thành công.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      summary: Thêm một cuốn sách mới
      description: Thêm một cuốn sách mới vào hệ thống.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
      responses:
        '201':
          description: Thêm sách thành công.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books/{id}:
    get:
      summary: Lấy thông tin chi tiết một sách
      description: Lấy thông tin chi tiết của sách theo ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID của sách cần lấy thông tin.
      responses:
        '200':
          description: Thông tin sách được trả về.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Không tìm thấy sách.

    put:
      summary: Cập nhật thông tin sách
      description: Cập nhật thông tin của một sách dựa theo ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID của sách cần cập nhật.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
      responses:
        '200':
          description: Cập nhật sách thành công.
        '404':
          description: Không tìm thấy sách để cập nhật.

    delete:
      summary: Xóa sách
      description: Xóa một sách theo ID khỏi hệ thống.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID của sách cần xóa.
      responses:
        '200':
          description: Xóa sách thành công.
        '404':
          description: Không tìm thấy sách để xóa.

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Harry Potter and the Philosopher's Stone
        author:
          type: string
          example: J.K. Rowling
        year:
          type: integer
          example: 1997
        genre:
          type: string
          example: Fantasy

    BookInput:
      type: object
      properties:
        title:
          type: string
          example: The Great Gatsby
        author:
          type: string
          example: F. Scott Fitzgerald
        year:
          type: integer
          example: 1925
        genre:
          type: string
          example: Classic
      required:
        - title
        - author
